// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/interfaces/primary/lesson_plan_manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/misalima/edunex-backend/internal/core/domain"
)

// MockLessonPlanManager is a mock of LessonPlanManager interface.
type MockLessonPlanManager struct {
	ctrl     *gomock.Controller
	recorder *MockLessonPlanManagerMockRecorder
}

// MockLessonPlanManagerMockRecorder is the mock recorder for MockLessonPlanManager.
type MockLessonPlanManagerMockRecorder struct {
	mock *MockLessonPlanManager
}

// NewMockLessonPlanManager creates a new mock instance.
func NewMockLessonPlanManager(ctrl *gomock.Controller) *MockLessonPlanManager {
	mock := &MockLessonPlanManager{ctrl: ctrl}
	mock.recorder = &MockLessonPlanManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLessonPlanManager) EXPECT() *MockLessonPlanManagerMockRecorder {
	return m.recorder
}

// CreateLessonPlan mocks base method.
func (m *MockLessonPlanManager) CreateLessonPlan(ctx context.Context, lp *domain.LessonPlan, fileReader io.Reader, filename, contentType string) (*domain.LessonPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLessonPlan", ctx, lp, fileReader, filename, contentType)
	ret0, _ := ret[0].(*domain.LessonPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLessonPlan indicates an expected call of CreateLessonPlan.
func (mr *MockLessonPlanManagerMockRecorder) CreateLessonPlan(ctx, lp, fileReader, filename, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLessonPlan", reflect.TypeOf((*MockLessonPlanManager)(nil).CreateLessonPlan), ctx, lp, fileReader, filename, contentType)
}

// GetLessonPlanWithSignedURL mocks base method.
func (m *MockLessonPlanManager) GetLessonPlanWithSignedURL(ctx context.Context, id uuid.UUID) (*domain.LessonPlan, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLessonPlanWithSignedURL", ctx, id)
	ret0, _ := ret[0].(*domain.LessonPlan)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLessonPlanWithSignedURL indicates an expected call of GetLessonPlanWithSignedURL.
func (mr *MockLessonPlanManagerMockRecorder) GetLessonPlanWithSignedURL(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLessonPlanWithSignedURL", reflect.TypeOf((*MockLessonPlanManager)(nil).GetLessonPlanWithSignedURL), ctx, id)
}

// ListLessonPlansWithSignedURLs mocks base method.
func (m *MockLessonPlanManager) ListLessonPlansWithSignedURLs(ctx context.Context) ([]*domain.LessonPlan, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLessonPlansWithSignedURLs", ctx)
	ret0, _ := ret[0].([]*domain.LessonPlan)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLessonPlansWithSignedURLs indicates an expected call of ListLessonPlansWithSignedURLs.
func (mr *MockLessonPlanManagerMockRecorder) ListLessonPlansWithSignedURLs(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLessonPlansWithSignedURLs", reflect.TypeOf((*MockLessonPlanManager)(nil).ListLessonPlansWithSignedURLs), ctx)
}
