// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/interfaces/primary/lesson_plan_manager.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	domain "github.com/misalima/edunex-backend/internal/core/domain"
)

// MockLessonPlanManager is a mock of LessonPlanManager interface.
type MockLessonPlanManager struct {
	ctrl     *gomock.Controller
	recorder *MockLessonPlanManagerMockRecorder
}

// MockLessonPlanManagerMockRecorder is the mock recorder for MockLessonPlanManager.
type MockLessonPlanManagerMockRecorder struct {
	mock *MockLessonPlanManager
}

// NewMockLessonPlanManager creates a new mock instance.
func NewMockLessonPlanManager(ctrl *gomock.Controller) *MockLessonPlanManager {
	mock := &MockLessonPlanManager{ctrl: ctrl}
	mock.recorder = &MockLessonPlanManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLessonPlanManager) EXPECT() *MockLessonPlanManagerMockRecorder {
	return m.recorder
}

// CreateLessonPlan mocks base method.
func (m *MockLessonPlanManager) CreateLessonPlan(ctx context.Context, lp *domain.LessonPlan, fileReader io.Reader, filename, contentType string) (*domain.LessonPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLessonPlan", ctx, lp, fileReader, filename, contentType)
	ret0, _ := ret[0].(*domain.LessonPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLessonPlan indicates an expected call of CreateLessonPlan.
func (mr *MockLessonPlanManagerMockRecorder) CreateLessonPlan(ctx, lp, fileReader, filename, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLessonPlan", reflect.TypeOf((*MockLessonPlanManager)(nil).CreateLessonPlan), ctx, lp, fileReader, filename, contentType)
}

// DeleteLessonPlan mocks base method.
func (m *MockLessonPlanManager) DeleteLessonPlan(ctx context.Context, userID, lessonPlanID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLessonPlan", ctx, userID, lessonPlanID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLessonPlan indicates an expected call of DeleteLessonPlan.
func (mr *MockLessonPlanManagerMockRecorder) DeleteLessonPlan(ctx, userID, lessonPlanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLessonPlan", reflect.TypeOf((*MockLessonPlanManager)(nil).DeleteLessonPlan), ctx, userID, lessonPlanID)
}

// GetAnalysisStatus mocks base method.
func (m *MockLessonPlanManager) GetAnalysisStatus(ctx context.Context, lessonPlanID uuid.UUID) (*domain.LessonPlanAnalysisStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalysisStatus", ctx, lessonPlanID)
	ret0, _ := ret[0].(*domain.LessonPlanAnalysisStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalysisStatus indicates an expected call of GetAnalysisStatus.
func (mr *MockLessonPlanManagerMockRecorder) GetAnalysisStatus(ctx, lessonPlanID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalysisStatus", reflect.TypeOf((*MockLessonPlanManager)(nil).GetAnalysisStatus), ctx, lessonPlanID)
}

// GetLessonPlanWithSignedURL mocks base method.
func (m *MockLessonPlanManager) GetLessonPlanWithSignedURL(ctx context.Context, id uuid.UUID) (*domain.LessonPlan, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLessonPlanWithSignedURL", ctx, id)
	ret0, _ := ret[0].(*domain.LessonPlan)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLessonPlanWithSignedURL indicates an expected call of GetLessonPlanWithSignedURL.
func (mr *MockLessonPlanManagerMockRecorder) GetLessonPlanWithSignedURL(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLessonPlanWithSignedURL", reflect.TypeOf((*MockLessonPlanManager)(nil).GetLessonPlanWithSignedURL), ctx, id)
}

// ListLessonPlansWithSignedURLs mocks base method.
func (m *MockLessonPlanManager) ListLessonPlansWithSignedURLs(ctx context.Context, userID uuid.UUID, params domain.PaginationParams) ([]*domain.LessonPlan, map[string]string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLessonPlansWithSignedURLs", ctx, userID, params)
	ret0, _ := ret[0].([]*domain.LessonPlan)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListLessonPlansWithSignedURLs indicates an expected call of ListLessonPlansWithSignedURLs.
func (mr *MockLessonPlanManagerMockRecorder) ListLessonPlansWithSignedURLs(ctx, userID, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLessonPlansWithSignedURLs", reflect.TypeOf((*MockLessonPlanManager)(nil).ListLessonPlansWithSignedURLs), ctx, userID, params)
}
