// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@edunex.example"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users/role": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the role of a user. Intended for admin users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Update user role",
                "parameters": [
                    {
                        "description": "Role update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_request.UpdateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analysis-jobs/metrics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns job processing metrics and statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Get job metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.JobMetricsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/analysis-jobs/{job_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the status of an analysis job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Get analysis job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.AnalysisJobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the API status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/lesson-plans": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns lesson plans for the authenticated user with pagination and signed URLs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lesson Plans"
                ],
                "summary": "List lesson plans",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max items per page (1-100, default 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.PaginatedLessonPlanResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads a lesson plan file and registers its metadata.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lesson Plans"
                ],
                "summary": "Create lesson plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lesson plan title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Teacher name",
                        "name": "teacher",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Discipline",
                        "name": "discipline",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Grade level",
                        "name": "grade_level",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Lesson plan file (.pdf or .docx)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lesson-plans/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a lesson plan and a signed download URL.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lesson Plans"
                ],
                "summary": "Get lesson plan by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lesson plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a lesson plan, its file, and associated analyses.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lesson Plans"
                ],
                "summary": "Delete a lesson plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lesson plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lesson-plans/{id}/analysis": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the status and structured pedagogical analysis when ready.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lesson Plans"
                ],
                "summary": "Get pedagogical analysis for a lesson plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lesson plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanAnalysisStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lesson-plans/{lesson_plan_id}/analyze": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enqueues a lesson plan for AI analysis processing in background",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analysis"
                ],
                "summary": "Analyze lesson plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lesson plan ID",
                        "name": "lesson_plan_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.EnqueueAnalysisResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get current authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the list of registered users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a user by its identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the name of a user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_request.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_request.UpdateRoleRequest": {
            "type": "object",
            "required": [
                "role",
                "user_id"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "example": "teacher"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_request.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Maria Silva"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.AnalysisJobResponse": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-16T15:30:00Z"
                },
                "error_message": {
                    "type": "string",
                    "example": "API timeout"
                },
                "finished_at": {
                    "type": "string",
                    "example": "2026-05-16T15:30:05Z"
                },
                "job_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "lesson_plan_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "started_at": {
                    "type": "string",
                    "example": "2026-05-16T15:30:01Z"
                },
                "status": {
                    "type": "string",
                    "example": "processing"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.EnqueueAnalysisResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "lesson_plan_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorMessageResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request payload"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "NOT_FOUND"
                },
                "message": {
                    "type": "string",
                    "example": "user not found"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.JobMetricsResponse": {
            "type": "object",
            "properties": {
                "active_workers": {
                    "type": "integer",
                    "example": 4
                },
                "db_stats": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "failed_jobs": {
                    "type": "integer",
                    "example": 2
                },
                "processed_jobs": {
                    "type": "integer",
                    "example": 42
                },
                "retried_jobs": {
                    "type": "integer",
                    "example": 3
                },
                "successful_jobs": {
                    "type": "integer",
                    "example": 40
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanAnalysisResponse": {
            "type": "object",
            "properties": {
                "alignment_score": {
                    "type": "integer",
                    "example": 85
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-16T15:30:00Z"
                },
                "feedback": {
                    "type": "string",
                    "example": "O plano está bem estruturado..."
                },
                "grade_level": {
                    "type": "string",
                    "example": "1ª SÉRIE"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "lesson_plan_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "metadata": {
                    "type": "string",
                    "example": "{\"objectives\": [\"Utilizar números inteiros\"]}"
                },
                "subject": {
                    "type": "string",
                    "example": "Matemática"
                },
                "suggestions": {
                    "type": "string",
                    "example": "[\"Adicionar atividades práticas\"]"
                },
                "title": {
                    "type": "string",
                    "example": "Plano de aula de Matemática"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanAnalysisStatusResponse": {
            "type": "object",
            "properties": {
                "analysis": {
                    "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanAnalysisResponse"
                },
                "error_message": {
                    "type": "string",
                    "example": ""
                },
                "status": {
                    "type": "string",
                    "example": "done"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-05-16T15:30:00Z"
                },
                "discipline": {
                    "type": "string",
                    "example": "Matemática"
                },
                "download_url": {
                    "type": "string",
                    "example": "https://storage.example.com/signed-url"
                },
                "grade_level": {
                    "type": "string",
                    "example": "1ª SÉRIE"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "teacher": {
                    "type": "string",
                    "example": "Ana Paula"
                },
                "title": {
                    "type": "string",
                    "example": "Plano de aula de Matemática"
                },
                "user_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user role updated successfully"
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.PaginatedLessonPlanResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_misalima_edunex-backend_internal_api_handlers_dto_response.LessonPlanResponse"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 47
                }
            }
        },
        "github_com_misalima_edunex-backend_internal_api_handlers_dto_response.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-05-16T15:30:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "maria@edunex.example"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Maria Silva"
                },
                "role": {
                    "type": "string",
                    "example": "teacher"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-05-16T15:30:00Z"
                }
            }
        },
        "internal_api_handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "API is running correctly!"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Edunex API",
	Description:      "API do backend do Edunex",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
